version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: true
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  grapql-mocker:
    image: cteklo/kotlin-docker:40
    ports:
      - '8081:8080'
    expose:
      - '8081'
  mq-mocker:
    image: cr.yandex/crpoieovuni5thn1fa4i/mq-mocker-server
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - KAFKA_ADDRESS=kafka
  rest-mocker:
    image: cr.yandex/crpoieovuni5thn1fa4i/rest-mocker-server
    ports:
      - '8889:8889'
    expose:
      - '8889'
    environment:
      - REST_MOCKER_DB_ADDRESS=db
  gateway:
    image: cr.yandex/crpoieovuni5thn1fa4i/gateway-server
    ports:
      - '9000:9000'
    expose:
      - '9000'
    environment:
      - MQ_MOCKER_ADDRESS=mq-mocker
      - REST_MOCKER_ADDRESS=rest-mocker
volumes:
  my-db:
