name: PR creation notifier

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Telegram PR created notification"    
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.actor }} created a PR:
            Repository: ${{ github.repository }}
            PR: https://github.com/${{ github.repository }}/pull/${{ github.event.number }} 

